# Generated by Django 4.2.11 on 2024-04-18 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chat",
            options={"ordering": ["last_modified"]},
        ),
    ]
