# Generated by Django 4.2.11 on 2024-04-19 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_message_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chat",
            old_name="name",
            new_name="chat_room",
        ),
    ]
