# Generated by Django 4.2.11 on 2024-04-21 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_rename_name_chat_chat_room"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="sender",
        ),
        migrations.DeleteModel(
            name="Chat",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
