# Generated by Django 4.2.11 on 2024-04-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="chat",
        ),
        migrations.RemoveField(
            model_name="message",
            name="sender",
        ),
        migrations.DeleteModel(
            name="Chat",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
