# Generated by Django 4.2.11 on 2024-04-18 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_follow"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="status",
            new_name="status_activity",
        ),
    ]
