# Generated by Django 4.2.11 on 2024-05-14 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_notification_like_or_comment_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="like_or_comment_user",
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
